In [2]:
import numpy as np

In [3]:
# Array accessing

arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[4])

arr = np.array([[6, 3], [0, 2]])
# Subarray
print(repr(arr[0]))

1
5
array([6, 3])


In [4]:
# slicing

NumPy arrays also support slicing. Similar to Python, we use the colon operator (i.e. arr[:]) for slicing. We can also use negative indexing to slice in the backwards direction.

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


For multi-dimensional arrays, we can use a comma to separate slices across each dimension.
The code below shows example slices of a 2-D NumPy array.

In [13]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(repr(arr[:]))
print(repr(arr[1:]))
# arr[axis0, axis1], arr[:, 0]
print(repr(arr[:, 0]))

print(repr(arr[:, 1:]))
print(repr(arr[0:1, 1:]))
print(repr(arr[0, 1:]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([1, 4, 7])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])


In [14]:
# argmin and argmax

figure out the actual indexes of the minimum and maximum elements

In [15]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(np.argmin(arr[0]))
print(np.argmax(arr[2])) # index of 9 at (0,1)
print(np.argmin(arr))

2
1
5


In [23]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
# axis=0 == vertical
# axis=1 == horizontal
print(arr.shape)
print(repr(np.argmin(arr, axis=0)))
print(repr(np.argmin(arr, axis=1)))
print(repr(np.argmax(arr, axis=-1)))
print(repr(np.argmax(arr, axis=1)))

(3, 3)
array([2, 0, 1])
array([2, 2, 0])
array([1, 1, 1])
array([1, 1, 1])


In our example, using axis=0 meant the function found the index of the minimum row element for each column. When we used axis=1, the function found the index of the minimum column element for each row.

Setting axis to -1 just means we apply the function across the last dimension. In this case, axis=-1 is equivalent to axis=1.